# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TAHRIR Coalition at the University of Michigan
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for the TAHRIR Coalition, which fights for Palestinian
  liberation at the University of Michigan. It includes organizations
  like Students Allied for Freedom and Equality, the U-M chapter of 
  Students for Justice in Palestine, and Jewish Voice for Peace.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tahrirxmich.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TAHRIRxmich
permalink: "/:categories/:title"
future: true
collections:
  research:
    output: true
    permalink: /:collection/:title
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list". 
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
